#!/bin/sh
awk_cmd="/usr/bin/awk"
CHROOT="/usr/sbin/chroot"
CP="/bin/cp"
DIFF="/usr/bin/diff"
FREEBSDUPDATE="/usr/sbin/freebsd-update"
FREEBSDVERSION="/bin/freebsd-version"
getopts_cmd="/usr/bin/getopts"
hostname_cmd="/bin/hostname"
jexec_cmd="/usr/sbin/jexec"
jls_cmd="/usr/sbin/jls"
SHA256="/sbin/sha256"

. colour

unset BYPASS
while getopts 'y' c
do
	case $c in
		y) BYPASS=true ;;
	esac
done
shift $((OPTIND-1))

COMMAND="$@"
COMMAND_FILE="$1"

if [ -e ${COMMAND_FILE} ]
then
	echo "No command specified."
	exit 1
fi

echo -e "Running the command ${UWhite}${COMMAND}${Color_Off} on following jails:"

JAILS=`${jls_cmd} | ${awk_cmd} '{if(NR>1)print $1}'`

for JAIL in ${JAILS}
do
	SYSTEMHOST=`${jexec_cmd} ${JAIL} ${hostname_cmd}`
	JAIL_PATH=`${jls_cmd} -j ${JAIL} | ${awk_cmd} '{if(NR>1)print $3}'`

	printf "${BIGreen}==>${Color_Off} ${BIPurple}${SYSTEMHOST}${Color_Off}: \"${BWhite}${COMMAND}${Color_Off}\"\n"
	if [ -e "${JAIL_PATH}${COMMAND_FILE}" ]
	then
		if [ ${BYPASS} ]
		then
			RUN="Y"
		else
			printf "${BIGreen}  >${Color_Off} Run? [y/N/q] "
			read RUN
			printf "\033[1A\033[2K"
		fi

		if [ "X${RUN}X" = "XYX" ] || [ "X${RUN}X" = "XyX" ]
		then
			printf "${BIGreen}==>${Color_Off} ${BIPurple}${SYSTEMHOST}${Color_Off}: ${BICyan}Running...${Color_Off}\n"
			(${jexec_cmd} ${JAIL} ${COMMAND})
			RET=$?

			if [ ${RET} -gt 0 ]
			then
				printf "${BIGreen}==>${Color_Off} ${BIPurple}${SYSTEMHOST}${Color_Off}: ${BIRed}Error.${Color_Off}\n"
				printf "${BIGreen}  >${Color_Off} Stop? [y/N] "
				read STOP
				printf "\033[1A\033[2K"

				if [ "X${STOP}X" = "XYX" ] || [ "X${STOP}X" = "XyX" ]
				then
					break
				fi
			else
				printf "${BIGreen}==>${Color_Off} ${BIPurple}${SYSTEMHOST}${Color_Off}: ${BICyan}Done.${Color_Off}\n\n"
			fi
		elif [ "X${RUN}X" = "XQX" ] || [ "X${RUN}X" = "XqX" ]
		then
			printf "${BIGreen}==>${Color_Off} ${BIPurple}${SYSTEMHOST}${Color_Off}: ${BBlue}Skipped.${Color_Off}\n\n"

			echo -n "Quiting! "
			break
		else
			printf "${BIGreen}==>${Color_Off} ${BIPurple}${SYSTEMHOST}${Color_Off}: ${BBlue}Skipped.${Color_Off}\n\n"
		fi
	else
		printf "${BIGreen}==>${Color_Off} ${BIPurple}${SYSTEMHOST}${Color_Off}: ${BBlue}Command not found.${Color_Off}\n\n"
	fi
done
echo "All done!"

exit 0
